version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./db-tmp:/var/lib/mysql
    - ./db-queries:/db-queries
